{
  "compatibilityLevel": 1550,
  "model": {
    "culture": "en-GB",
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "sourceQueryCulture": "en-GB",
    "tables": [
      {
        "name": "Sales",
        "columns": [
          {
            "name": "Month",
            "dataType": "string",
            "sourceColumn": "Month",
            "summarizeBy": "none",
            "isHidden": false,
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "MonthNo",
            "dataType": "int64",
            "sourceColumn": "MonthNo",
            "summarizeBy": "none",
            "isHidden": false,
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "RevenueValue",
            "dataType": "double",
            "sourceColumn": "RevenueValue",
            "summarizeBy": "none",
            "isHidden": false,
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "TicketsValue",
            "dataType": "int64",
            "sourceColumn": "TicketsValue",
            "summarizeBy": "none",
            "isHidden": false,
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "OnTimeValue",
            "dataType": "double",
            "sourceColumn": "OnTimeValue",
            "summarizeBy": "none",
            "isHidden": false,
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "measures": [
          {
            "name": "Revenue",
            "expression": "SUM('Sales'[RevenueValue])",
            "formatString": "#,0"
          },
          {
            "name": "Revenue change",
            "expression": "VAR cur = CALCULATE ( SUM ( 'Sales'[RevenueValue] ), 'Sales'[MonthNo] = MAX ( 'Sales'[MonthNo] ) )\nVAR prev = CALCULATE ( SUM ( 'Sales'[RevenueValue] ), 'Sales'[MonthNo] = MAX ( 'Sales'[MonthNo] ) - 1 )\nRETURN DIVIDE ( cur - prev, prev )",
            "formatString": "0.0%"
          },
          {
            "name": "Open tickets",
            "expression": "CALCULATE ( SUM ( 'Sales'[TicketsValue] ), 'Sales'[MonthNo] = MAX ( 'Sales'[MonthNo] ) )",
            "formatString": "#,0"
          },
          {
            "name": "Tickets change",
            "expression": "CALCULATE ( SUM ( 'Sales'[TicketsValue] ), 'Sales'[MonthNo] = MAX ( 'Sales'[MonthNo] ) )\n    - CALCULATE ( SUM ( 'Sales'[TicketsValue] ), 'Sales'[MonthNo] = MAX ( 'Sales'[MonthNo] ) - 1 )",
            "formatString": "#,0"
          },
          {
            "name": "On time",
            "expression": "CALCULATE ( AVERAGE ( 'Sales'[OnTimeValue] ), 'Sales'[MonthNo] = MAX ( 'Sales'[MonthNo] ) )",
            "formatString": "0.0%"
          },
          {
            "name": "On time change",
            "expression": "CALCULATE ( AVERAGE ( 'Sales'[OnTimeValue] ), 'Sales'[MonthNo] = MAX ( 'Sales'[MonthNo] ) )\n    - CALCULATE ( AVERAGE ( 'Sales'[OnTimeValue] ), 'Sales'[MonthNo] = MAX ( 'Sales'[MonthNo] ) - 1 )",
            "formatString": "0.0%"
          },
          {
            "name": "Overdue actions",
            "expression": "BLANK()"
          },
          {
            "name": "YTD",
            "expression": "\"YTD\""
          },
          {
            "name": "This week",
            "expression": "\"this week\""
          },
          {
            "name": "This month",
            "expression": "\"this month\""
          }
        ],
        "partitions": [
          {
            "name": "Sales",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"Tc3RDcAgCATQXfi2DSKgztK4/xrlgiZ+nCHkcX4fCYs/3KgQIs2ZOQaTePidVmmVozR2iCin0r7VuJThPLsCQmkqn5fy2CEyTtdM1e1S6Edk1u5Qbf/oSmv9\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Month = _t, MonthNo = _t, RevenueValue = _t, TicketsValue = _t, OnTimeValue = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Month\", type text}, {\"MonthNo\", Int64.Type}, {\"RevenueValue\", type number}, {\"TicketsValue\", Int64.Type}, {\"OnTimeValue\", type number}})",
                "in",
                "    #\"Changed Type\""
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      }
    ],
    "relationships": [],
    "annotations": [
      {
        "name": "PBI_QueryOrder",
        "value": "[\"Sales\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "0"
      }
    ]
  }
}
